spring.application.name=PanVerification

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-wild-cloud-aogfhnro-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_pgEBVJCc6R8S}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

opv.pfx-file=${OPV_PFX_FILE:src/main/resources/certs/output.jks}
opv.pfx-password=${OPV_PFX_PASSWORD:abc1234}

# Increase connection timeout
spring.mvc.async.request-timeout=60000

protean.user-id=${PROTEAN_USER_ID:V0024301}
protean.version=${PROTEAN_VERSION:4}
protean.uat-url=${PROTEAN_UAT_URL:https://121.240.36.237/TIN/PanInquiryAPIBackEnd}

jwt.secret=${JWT_SECRET:1234567890123456789012345678901234567890123456789012345678901234}
logging.level.root=INFO

logging.level.com.verify.panverification=DEBUG