spring.application.name=PanVerification

spring.datasource.url=jdbc:postgresql://ep-wild-cloud-aogfhnro-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_pgEBVJCc6R8S
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
opv.pfx-file=certs/output.jks
opv.pfx-password=abc1234

protean.user-id=V0024301
protean.version=4
protean.uat-url=https://121.240.36.237/TIN/PanInquiryAPIBackEnd

jwt.secret=1234567890123456789012345678901234567890123456789012345678901234

logging.level.root=INFO

logging.level.com.verify.panverification=DEBUG